name: Designer Publish
on:
  repository_dispatch:
    types: [release_designer_service]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATION_PAT }}
          PACKAGEJSON_DIR: './libs/designer'
        with:
          bump-policy: 'ignore'
          commit-message: 'CI: bumps Designer version to {{version}} [skip ci]'
          tag-prefix: 'designer@v'

      - run: npm ci
      - run: npm run build

      - name: Use .npmrc
        uses: bduff9/use-npmrc@v1.1
        with:
          dot-npmrc: ${{ secrets.PUBLISHING_PAT }}
          working-directory: './dist/libs/designer'

      - run: cd ./dist/libs/designer && npm publish
